-- ============================================================
-- StudySpot Booking Portal — Live Schema & Policies
-- ============================================================

-- 1. TABLES (Matched to Live DB) ------------------------------

CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS floors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
  floor_number INT NOT NULL,
  room_no TEXT, -- Legacy
  room_name TEXT, -- Legacy
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rooms (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  floor_id BIGINT REFERENCES floors(id) ON DELETE CASCADE,
  room_no TEXT NOT NULL,
  name TEXT,
  is_ac BOOLEAN DEFAULT false,
  price_daily INTEGER DEFAULT 0,
  seats_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
  seat_no TEXT NOT NULL,
  is_blocked BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS slots (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  duration_days INT NOT NULL,
  price INT NOT NULL,
  is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  slot_id TEXT REFERENCES slots(id),
  branch_id BIGINT REFERENCES branches(id),
  floor_id BIGINT REFERENCES floors(id),
  seat_id BIGINT REFERENCES seats(id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  amount INT NOT NULL,
  payment_screenshot_url TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL
);

-- 2. VIEWS ----------------------------------------------------

CREATE OR REPLACE VIEW available_seats AS
SELECT
  s.id,
  s.seat_no,
  s.is_blocked,
  s.room_id,
  r.floor_id,
  f.branch_id,
  f.floor_number,
  CASE
    WHEN s.is_blocked THEN false
    WHEN EXISTS (
      SELECT 1 FROM bookings b
      WHERE b.seat_id = s.id
        AND b.status IN ('confirmed', 'pending')
        AND b.start_date <= CURRENT_DATE
        AND b.end_date >= CURRENT_DATE
    ) THEN false
    ELSE true
  END AS is_available
FROM seats s
JOIN rooms r ON s.room_id = r.id
JOIN floors f ON r.floor_id = f.id;

-- 3. TRIGGERS -------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_bookings_updated_at ON bookings;
CREATE TRIGGER update_bookings_updated_at
BEFORE UPDATE ON bookings
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 4. ROW LEVEL SECURITY (Policies) ---------------------------

ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE floors ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Public read policies
CREATE POLICY "public_read_branches" ON branches FOR SELECT USING (true);
CREATE POLICY "public_read_floors" ON floors FOR SELECT USING (true);
CREATE POLICY "public_read_rooms" ON rooms FOR SELECT USING (true);
CREATE POLICY "public_read_seats" ON seats FOR SELECT USING (true);
CREATE POLICY "public_read_slots" ON slots FOR SELECT USING (true);

-- Booking policies
CREATE POLICY "public_insert_bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "public_read_bookings" ON bookings FOR SELECT USING (true);

-- Admin policies
CREATE POLICY "admin_update_bookings" ON bookings FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "admin_update_seats" ON seats FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "admin_update_rooms" ON rooms FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "admin_update_slots" ON slots FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "admin_insert_slots" ON slots FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_read_admins" ON admins FOR SELECT USING (auth.role() = 'authenticated');

-- 5. CRON JOBS ------------------------------------------------
-- (Reference from your setup)

-- SELECT cron.schedule(
--   'expire-bookings',
--   '0 0 * * *',
--   $$UPDATE bookings SET status = 'expired' WHERE status = 'confirmed' AND end_date < CURRENT_DATE;$$
-- );
--
-- SELECT cron.schedule(
--   'cleanup-screenshots',
--   '0 3 * * *',
--   $$UPDATE bookings SET payment_screenshot_url = NULL WHERE status = 'confirmed' AND payment_screenshot_url IS NOT NULL AND updated_at < NOW() - INTERVAL '2 days';$$
-- );

-- 6. SEED DATA (Reference) ------------------------------------

-- INSERT INTO branches (id, name, address) VALUES
--   (1, 'Branch 1 — Koramangala', '4th Block, Koramangala'),
--   (2, 'Branch 2 — Indiranagar', '100 Feet Road, Indiranagar')
-- ON CONFLICT DO NOTHING;
-- ... (See previous backups for full seed data if needed)
